# Generated by Django 5.2.5 on 2025-09-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='reconciled_at',
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='bankreconciliation',
            table=None,
        ),
    ]
