# Generated by Django 5.2.5 on 2025-09-19 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_financialperiod_options_journalentry_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='inventory_adjustment_gain_account',
            field=models.ForeignKey(blank=True, help_text='The revenue/other income account for inventory overages.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Inventory Adjustment Gain Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='inventory_adjustment_loss_account',
            field=models.ForeignKey(blank=True, help_text='The expense account for inventory shortages/shrinkage.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Inventory Adjustment Loss Account'),
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(verbose_name='Count Date')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending_allocation', 'Pending Allocation'), ('completed', 'Completed')], default='in_progress', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason for Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Inventory Count',
                'verbose_name_plural': 'Inventory Counts',
                'db_table': 'inventory_counts',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_quantity', models.FloatField(help_text='Use a negative number for shortages and a positive number for overages.', verbose_name='Adjustment Quantity')),
                ('adjustment_date', models.DateTimeField(verbose_name='Adjustment Date')),
                ('cost_at_adjustment', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cost at Time of Adjustment')),
                ('reason_code', models.CharField(choices=[('shrinkage', 'Shrinkage/Loss'), ('damage', 'Damaged Goods'), ('data_entry_error', 'Data Entry Correction'), ('overage_found', 'Overage Found During Count'), ('other', 'Other')], max_length=30, verbose_name='Reason Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.product', verbose_name='Product')),
                ('source_finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.finishedproductreceipt', verbose_name='Source Finished Product Receipt')),
                ('source_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventorylog', verbose_name='Source Inventory Log (Raw Material)')),
                ('inventory_count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='inventory.inventorycount', verbose_name='Originating Inventory Count')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'db_table': 'inventory_adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.FloatField(verbose_name='System Quantity at Time of Count')),
                ('counted_quantity', models.FloatField(blank=True, null=True, verbose_name='Physically Counted Quantity')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycount', verbose_name='Inventory Count')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_items', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Count Item',
                'verbose_name_plural': 'Inventory Count Items',
                'db_table': 'inventory_count_items',
                'unique_together': {('inventory_count', 'product')},
            },
        ),
    ]
