# Generated by Django 5.2.5 on 2025-09-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryadjustment_is_posted_to_gl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='is_posted_to_gl',
        ),
    ]
