# Generated by Django 5.2.5 on 2025-09-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0008_remove_inventoryadjustment_is_posted_to_gl'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_logged', to='inventory.employee', verbose_name='Responsible Employee'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='employee_advances_receivable',
            field=models.ForeignKey(blank=True, help_text='The asset account for tracking money given to employees.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Employee Advances Receivable Account'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receipts', to='inventory.employee', verbose_name='Responsible Employee'),
        ),
        migrations.CreateModel(
            name='CostPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cost Pool Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Cost Pool Code')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.costpool', verbose_name='Parent Cost Pool')),
            ],
            options={
                'verbose_name': 'Cost Pool',
                'verbose_name_plural': 'Cost Pools',
                'db_table': 'cost_pools',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='expenselog',
            name='cost_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='inventory.costpool', verbose_name='Cost Pool'),
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_date', models.DateField(verbose_name='Advance Date')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_settled', 'Partially Settled'), ('settled', 'Settled')], default='open', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='inventory.employee', verbose_name='Employee')),
                ('source_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_advance', to='inventory.payment', verbose_name='Source Payment Transaction')),
            ],
            options={
                'verbose_name': 'Employee Advance',
                'verbose_name_plural': 'Employee Advances',
                'db_table': 'employee_advances',
                'ordering': ['-advance_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvanceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_settled', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount Settled')),
                ('settlement_date', models.DateField(auto_now_add=True, verbose_name='Settlement Date')),
                ('object_id', models.PositiveIntegerField()),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='inventory.employeeadvance', verbose_name='Employee Advance')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Employee Advance Settlement',
                'verbose_name_plural': 'Employee Advance Settlements',
                'db_table': 'employee_advance_settlements',
                'ordering': ['-settlement_date'],
            },
        ),
    ]
