# Generated by Django 5.2.5 on 2025-09-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_expenselog_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Driver Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Allocation Driver',
                'verbose_name_plural': 'Allocation Drivers',
                'db_table': 'allocation_drivers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='machine_hours_consumed',
            field=models.FloatField(blank=True, help_text='Enter the actual machine hours used for this production run.', null=True, verbose_name='Machine Hours Consumed'),
        ),
        migrations.CreateModel(
            name='OverheadAllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pool_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Total Pool Amount for Period')),
                ('total_driver_units', models.FloatField(verbose_name='Total Driver Units for Period')),
                ('calculated_rate', models.DecimalField(decimal_places=5, max_digits=14, verbose_name='Calculated Overhead Rate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Rate Calculated'), ('posted', 'Posted to GL')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('allocation_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_runs', to='inventory.allocationdriver', verbose_name='Allocation Driver')),
                ('cost_pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_runs', to='inventory.costpool', verbose_name='Cost Pool')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_runs', to='inventory.financialperiod', verbose_name='Financial Period')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Resulting Journal Entry')),
            ],
            options={
                'verbose_name': 'Overhead Allocation Run',
                'verbose_name_plural': 'Overhead Allocation Runs',
                'db_table': 'overhead_allocation_runs',
                'ordering': ['-financial_period__start_date', 'cost_pool__code'],
                'unique_together': {('financial_period', 'cost_pool')},
            },
        ),
    ]
