# Generated by Django 5.2.5 on 2025-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_batch_options_batch_labor_hours_consumed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationdriver',
            options={'verbose_name': 'Allocation Driver', 'verbose_name_plural': 'Allocation Drivers'},
        ),
        migrations.AddField(
            model_name='shopordertemplate',
            name='bottle_size_ml',
            field=models.PositiveIntegerField(blank=True, help_text='For overhead allocation based on volume, enter the size of a single bottle/unit in milliliters.', null=True, verbose_name='Bottle Size (mL)'),
        ),
        migrations.AlterField(
            model_name='allocationdriver',
            name='name',
            field=models.CharField(choices=[('Machine Hours', 'Machine Hours'), ('Labor Hours', 'Labor Hours'), ('Total Production Units (Bottles)', 'Total Production Units (Bottles)'), ('Total Production Volume (Liters)', 'Total Production Volume (Liters)')], max_length=255, unique=True, verbose_name='Driver Name'),
        ),
    ]
