# Generated by Django 5.2.5 on 2025-09-25 15:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_allocationdriver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overheadallocationrun',
            name='calculated_rate',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=14, verbose_name='Calculated Overhead Rate'),
        ),
        migrations.AlterField(
            model_name='overheadallocationrun',
            name='total_driver_units',
            field=models.FloatField(default=0.0, verbose_name='Total Driver Units for Period'),
        ),
        migrations.AlterField(
            model_name='overheadallocationrun',
            name='total_pool_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=14, verbose_name='Total Pool Amount for Period'),
        ),
    ]
