# Generated by Django 5.2.5 on 2025-09-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_overheadallocationrun_application_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costpool',
            name='gl_account',
            field=models.ForeignKey(blank=True, help_text="The specific expense account in the GL that this pool's costs are cleared to.", limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_pools', to='inventory.account', verbose_name='GL Expense Account'),
        ),
        migrations.DeleteModel(
            name='ExpenseCategoryAccountingSettings',
        ),
    ]
