# Generated by Django 5.2.5 on 2025-09-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_costpool_gl_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproductreceipt',
            name='bottle_size_ml',
        ),
        migrations.RemoveField(
            model_name='finishedproductreceipt',
            name='number_of_bottles',
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='scrap_expense_account',
            field=models.ForeignKey(blank=True, help_text='The expense account for writing off scrapped inventory.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Scrap Expense Account'),
        ),
    ]
