# Generated by Django 5.2.5 on 2025-09-29 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0019_account_is_control_account_account_sub_ledger_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('correction_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Correction Timestamp')),
                ('justification', models.TextField(verbose_name='Justification for Correction')),
                ('adjusting_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_source', to='inventory.journalentry', verbose_name='Adjusting Journal Entry')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Corrected By')),
            ],
            options={
                'verbose_name': 'Transaction Correction',
                'verbose_name_plural': 'Transaction Corrections',
                'ordering': ['-correction_timestamp'],
                'permissions': [('can_create_transaction_correction', 'Can create a correction for a posted transaction')],
            },
        ),
    ]
