# Generated by Django 5.0.4 on 2024-07-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_batchitem_source_type_alter_fixedasset_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodCloseChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_depreciation_run', models.BooleanField(default=False, help_text='Indicates if the monthly depreciation for all fixed assets has been calculated and posted.', verbose_name='Depreciation Run')),
                ('is_overhead_posted', models.BooleanField(default=False, help_text='Indicates if manufacturing overhead costs have been allocated and posted to WIP.', verbose_name='Overhead Posted')),
                ('all_banks_reconciled', models.BooleanField(default=False, help_text='Indicates if all bank accounts have been reconciled for the period.', verbose_name='All Banks Reconciled')),
                ('no_draft_manual_jes', models.BooleanField(default=False, help_text='Ensures no manually created journal entries are left in draft status.', verbose_name='No Draft Manual JEs')),
                ('no_unposted_invoices', models.BooleanField(default=False, help_text='Ensures all supplier and customer invoices for the period have been posted.', verbose_name='No Unposted Invoices')),
                ('is_inventory_valuation_run', models.BooleanField(default=True, help_text='Placeholder for inventory valuation process completion.', verbose_name='Inventory Valuation Run')),
                ('financial_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='inventory.financialperiod', verbose_name='Financial Period')),
            ],
            options={
                'verbose_name': 'Period Close Checklist',
                'verbose_name_plural': 'Period Close Checklists',
            },
        ),
    ]
