# Generated by Django 5.0.4 on 2024-07-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_periodclosechecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentapplication',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.customerinvoice', verbose_name='Invoice'),
        ),
    ]
