# Generated by Django 5.2.5 on 2025-10-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0025_alter_periodclosechecklist_all_banks_reconciled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpaymentapplication',
            options={},
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='accrued_expenses_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Accrued Expenses Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='customer_deposits_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Customer Deposits / Deferred Revenue Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='damaged_goods_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Damaged Goods / Scrap Expense Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='prepaid_expenses_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Prepaid Expenses Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='sales_returns_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Sales Returns & Allowances Account'),
        ),
        migrations.AlterUniqueTogether(
            name='customerpaymentapplication',
            unique_together={('payment', 'invoice')},
        ),
        migrations.AlterModelTable(
            name='customerpaymentapplication',
            table=None,
        ),
        migrations.CreateModel(
            name='CustomerCreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_number', models.CharField(max_length=100, unique=True)),
                ('memo_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unapplied_amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partially_applied', 'Partially Applied'), ('applied', 'Applied')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos', to='inventory.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Inspection'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='inventory.customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.FloatField()),
                ('disposition', models.CharField(blank=True, choices=[('stock', 'Return to Stock'), ('scrap', 'Scrap')], max_length=20, null=True)),
                ('original_dispatch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.finishedproductdispatch')),
                ('reversing_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.journalentry')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salesreturn')),
            ],
        ),
    ]
