# Generated by Django 5.2.5 on 2025-10-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_customerpaymentapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='inventory_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventorycount', verbose_name='Inventory Count Event'),
        ),
    ]
