# Generated by Django 5.2.5 on 2025-10-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_inventoryadjustment_inventory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitem',
            name='journal_entries',
            field=models.ManyToManyField(blank=True, related_name='sales_return_items_sources', to='inventory.journalentry'),
        ),
    ]
