# Generated by Django 5.2.5 on 2025-10-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_salesreturnitem_journal_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='journal_entries',
        ),
    ]
