# Generated by Django 5.2.5 on 2025-10-03 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0030_inventoryconsumption_cost_pool_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaidexpense',
            name='source_consumption',
        ),
        migrations.RemoveField(
            model_name='prepaidexpense',
            name='source_payment',
        ),
        migrations.RemoveField(
            model_name='prepaidexpense',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='asset_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Asset Control Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expenses_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='description',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='initial_amount',
            field=models.DecimalField(decimal_places=3, default=8, max_digits=14, verbose_name='Initial Prepaid Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='source_object_id',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costpoolsplit',
            name='cost_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.costpool', verbose_name='Cost Pool'),
        ),
        migrations.AlterField(
            model_name='inventoryconsumption',
            name='consumption_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Capitalize', 'Capitalize'), ('Amortize', 'Amortize')], default='Expense', max_length=20, verbose_name='Consumption Type'),
        ),
        migrations.AlterField(
            model_name='inventoryconsumption',
            name='department',
            field=models.CharField(choices=[('Production', 'Production'), ('Engineering', 'Engineering'), ('Quality Control', 'Quality Control'), ('Warehouse', 'Warehouse')], max_length=50, verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('request_type', models.CharField(choices=[('DIRECT_EXPENSE', 'Direct Expense'), ('INVENTORY_EXPENSE', 'Inventory Consumption to Expense'), ('INVENTORY_CAPITALIZE', 'Inventory Consumption to Capitalize'), ('INVENTORY_PREPAID', 'Inventory Consumption to Prepaid'), ('INVOICE_PREPAID', 'Prepaid Expense from Invoice')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('request_date', models.DateField(help_text='The intended date of the expense.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('category', models.CharField(blank=True, choices=[('salaries', 'رواتب وأجور'), ('utilities', 'كهرباء ومياه واتصالات'), ('rent', 'إيجارات'), ('marketing', 'تسويق وإعلان'), ('transport', 'نقل وشحن'), ('maintenance', 'صيانة (خدمات خارجية)'), ('fees', 'رسوم حكومية وتراخيص'), ('other', 'مصاريف أخرى')], max_length=50, null=True)),
                ('classification', models.CharField(blank=True, choices=[('manufacturing_overhead', 'تكاليف صناعية غير مباشرة'), ('sg_a', 'مصاريف بيعية وعمومية وإدارية')], max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('amortization_start_date', models.DateField(blank=True, null=True)),
                ('amortization_end_date', models.DateField(blank=True, null=True)),
                ('asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account')),
                ('cost_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.costpool')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account')),
                ('fixed_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.fixedasset')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests_processed', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests_made', to=settings.AUTH_USER_MODEL)),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplierinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='expenselog',
            name='source_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_expense_logs', to='inventory.expenserequest'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='source_request',
            field=models.OneToOneField(blank=True, help_text='The approved request that triggered this consumption.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_consumption', to='inventory.expenserequest'),
        ),
    ]
