# Generated by Django 5.2.5 on 2025-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_prepaidexpense_source_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('PACKAGING', 'Packaging'), ('FINAL_PRODUCT', 'Final Product'), ('MRO', 'MRO (Maintenance, Repair, Operations)'), ('CONSUMABLE', 'Consumable')], max_length=50, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='producttypeaccountingsettings',
            name='product_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('PACKAGING', 'Packaging'), ('FINAL_PRODUCT', 'Final Product'), ('MRO', 'MRO (Maintenance, Repair, Operations)'), ('CONSUMABLE', 'Consumable')], max_length=50, unique=True, verbose_name='Product Type'),
        ),
    ]
