# Generated by Django 5.2.5 on 2025-10-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0036_alter_expenserequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselog',
            name='settlement_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='settlement_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='settlement_status',
            field=models.CharField(choices=[('UNSETTLED', 'Unsettled'), ('SETTLED', 'Settled')], default='UNSETTLED', max_length=20, verbose_name='Settlement Status'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Required if settlement method is Direct Payment.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.bankaccount'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('ACCRUE_AND_PAY_LATER', 'Accrue and Pay via Supplier Invoice'), ('DIRECT_PAYMENT', 'Direct Payment from Bank/Cash')], help_text='Required for Direct Expense requests.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Required if settlement method is Accrue and Pay Later.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
    ]
