# Generated by Django 5.2.5 on 2025-10-09 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_expenselog_settlement_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='expense_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.expenselog', verbose_name='Expense Log'),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylog', verbose_name='Inventory Receipt (Log)'),
        ),
    ]
