# Generated by Django 5.2.5 on 2025-10-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0038_supplierinvoiceitem_expense_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselog',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_logs', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
