# Generated by Django 5.2.5 on 2025-10-10 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_expenselog_source_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvancesettlement',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_advance_settlement', to='inventory.journalentry'),
        ),
    ]
