# Generated by Django 5.2.5 on 2025-10-10 12:00

from django.db import migrations, models
import django.db.models.deletion
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_employeeadvancesettlement_journal_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accruedexpense',
            old_name='estimated_monthly_amount',
            new_name='total_estimated_amount',
        ),
        migrations.AddField(
            model_name='accruedexpense',
            name='accrual_end_date',
            field=models.DateField(default='2025-12-31', verbose_name='Accrual End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accruedexpense',
            name='accrual_start_date',
            field=models.DateField(default='2025-01-01', verbose_name='Accrual Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accruedexpense',
            name='source_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accrual', to='inventory.expenserequest', verbose_name='Source Expense Request'),
        ),
    ]
