# Generated by Django 5.2.5 on 2025-10-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnitem',
            name='original_dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.finishedproductdispatch'),
        ),
    ]
