# Generated by Django 5.2.5 on 2025-10-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_salesreturnitem_original_dispatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='reversing_journal_entry',
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='sales_returns_clearing_account',
            field=models.ForeignKey(blank=True, help_text='A temporary account to balance COGS reversal and final disposition of returns.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Sales Returns Clearing Account'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='source_sales_return_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment', to='inventory.salesreturnitem', verbose_name='Source Sales Return Item'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='cogs_reversal_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='COGS Reversal Journal Entry'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason_code',
            field=models.CharField(choices=[('shrinkage', 'Shrinkage/Loss'), ('damage', 'Damaged Goods'), ('data_entry_error', 'Data Entry Correction'), ('overage_found', 'Overage Found During Count'), ('sales_return_stock', 'Return to Stock from Sale'), ('other', 'Other')], max_length=30, verbose_name='Reason Code'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='status',
            field=models.CharField(choices=[('pending_inspection', 'Pending Inspection'), ('pending_processing', 'Pending Processing'), ('completed', 'Completed')], default='pending_inspection', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='disposition',
            field=models.CharField(blank=True, choices=[('return_to_stock', 'Return to Stock'), ('scrap', 'Scrap')], max_length=20, null=True),
        ),
    ]
