# Generated by Django 5.2.5 on 2025-10-18 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_remove_salesreturnitem_reversing_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Landed Cost Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Landed Cost Type',
                'verbose_name_plural': 'Landed Cost Types',
                'db_table': 'landed_cost_types',
            },
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='goods_received_not_invoiced_account',
            field=models.ForeignKey(blank=True, help_text='A temporary liability account for received goods before the supplier invoice is posted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Goods Received Not Invoiced (GRNI) Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='purchase_price_variance_account',
            field=models.ForeignKey(blank=True, help_text='An expense account to record differences between PO price and actual invoice price.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Purchase Price Variance (PPV) Account'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='actual_subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Actual Subtotal (from Invoice)'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='actual_vat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Actual VAT (from Invoice)'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Posting Journal Entry'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason_code',
            field=models.CharField(choices=[('shrinkage', 'نقص/خسارة'), ('damage', 'بضاعة تالفة'), ('data_entry_error', 'تصحيح خطأ إدخال بيانات'), ('overage_found', 'زيادة وجدت أثناء الجرد'), ('sales_return_stock', 'إرجاع إلى المخزون من المبيعات'), ('other', 'أخرى')], max_length=30, verbose_name='Reason Code'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(verbose_name='Return Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='inventory.company', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'db_table': 'purchase_returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.FloatField(verbose_name='Quantity Returned')),
                ('original_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='inventory.inventorylog', verbose_name='Original Receipt Log')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereturn', verbose_name='Purchase Return')),
            ],
            options={
                'verbose_name': 'Purchase Return Item',
                'verbose_name_plural': 'Purchase Return Items',
                'db_table': 'purchase_return_items',
            },
        ),
        migrations.CreateModel(
            name='SupplierDebitMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_number', models.CharField(max_length=100, verbose_name='Debit Memo Number')),
                ('memo_date', models.DateField(verbose_name='Memo Date')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('applied', 'Applied')], default='open', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Journal Entry')),
                ('purchase_return', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_memo', to='inventory.purchasereturn', verbose_name='Source Purchase Return')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_memos', to='inventory.company', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Debit Memo',
                'verbose_name_plural': 'Supplier Debit Memos',
                'db_table': 'supplier_debit_memos',
                'unique_together': {('supplier', 'memo_number')},
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLandedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.landedcosttype', verbose_name='Cost Type')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_costs', to='inventory.supplierinvoice', verbose_name='Supplier Invoice')),
            ],
            options={
                'verbose_name': 'Supplier Invoice Landed Cost',
                'verbose_name_plural': 'Supplier Invoice Landed Costs',
                'db_table': 'supplier_invoice_landed_costs',
                'unique_together': {('invoice', 'cost_type')},
            },
        ),
    ]
