# Generated by Django 5.2.5 on 2025-10-18 19:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_landedcosttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='costing_unit_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='The final unit cost for inventory valuation, including capitalized VAT and landed costs.', max_digits=14, verbose_name='Costing Unit Price'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='landed_cost_component',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='The portion of the unit price that is from allocated landed costs.', max_digits=14, verbose_name='Landed Cost Component'),
        ),
    ]
