# Generated by Django 5.2.5 on 2025-10-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_purchaseorderitem_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='landed_costs_clearing_account',
            field=models.ForeignKey(blank=True, help_text='A temporary account to hold third-party landed costs before they are allocated to inventory.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Landed Costs Clearing Account'),
        ),
        migrations.CreateModel(
            name='LandedCostInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_allocation', 'Awaiting Allocation'), ('fully_allocated', 'Fully Allocated')], default='draft', max_length=25, verbose_name='Status')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Journal Entry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_invoices', to='inventory.company', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Landed Cost Invoice',
                'verbose_name_plural': 'Landed Cost Invoices',
                'db_table': 'landed_cost_invoices',
                'unique_together': {('vendor', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='LandedCostInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.landedcosttype', verbose_name='Cost Type')),
                ('landed_cost_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.landedcostinvoice', verbose_name='Landed Cost Invoice')),
            ],
            options={
                'verbose_name': 'Landed Cost Invoice Item',
                'verbose_name_plural': 'Landed Cost Invoice Items',
                'db_table': 'landed_cost_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Allocated Amount')),
                ('allocation_date', models.DateTimeField(auto_now_add=True, verbose_name='Allocation Date')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Allocation Journal Entry')),
                ('receipt_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_allocations', to='inventory.inventorylog', verbose_name='Inventory Receipt')),
                ('landed_cost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.landedcostinvoiceitem', verbose_name='Landed Cost Item')),
            ],
            options={
                'verbose_name': 'Landed Cost Allocation',
                'verbose_name_plural': 'Landed Cost Allocations',
                'db_table': 'landed_cost_allocations',
            },
        ),
    ]
