# Generated by Django 5.2.5 on 2025-10-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_generalaccountingsettings_landed_costs_clearing_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='purchase_returns_clearing_account',
            field=models.ForeignKey(blank=True, help_text='A temporary account to hold the value of returned goods before a debit memo is issued.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Purchase Returns Clearing Account'),
        ),
        migrations.DeleteModel(
            name='SupplierInvoiceLandedCost',
        ),
    ]
