# Generated by Django 5.2.5 on 2025-10-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_generalaccountingsettings_purchase_returns_clearing_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalaccountingsettings',
            name='purchase_returns_clearing_account',
            field=models.ForeignKey(blank=True, help_text="e.g., '20207 - تسوية مرتجعات موردين'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Purchase Returns Clearing Account'),
        ),
    ]
