# Generated by Django 5.2.5 on 2025-10-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_alter_generalaccountingsettings_purchase_returns_clearing_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='finishedproductdispatch',
            name='finished_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='inventory.finishedproductreceipt', verbose_name='Finished Product Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finishedproductdispatch',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='inventory_revaluation_account',
            field=models.ForeignKey(blank=True, help_text='An account to record upward or downward adjustments to inventory value from late costs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Inventory Revaluation Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='manufacturing_variance_account',
            field=models.ForeignKey(blank=True, help_text='An account to record differences between standard/expected cost and actual production cost.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Manufacturing Variance Account'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='productionreturn',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_returns', to='inventory.batch', verbose_name='Source Batch'),
        ),
        migrations.AddField(
            model_name='productionreturn',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='status',
            field=models.CharField(choices=[('quarantined', 'تحت الفحص'), ('released', 'مفرج عنه'), ('rejected', 'مرفوض'), ('scrapped', 'خردة'), ('voided', 'ملغي')], default='quarantined', max_length=20, verbose_name='Status'),
        ),
    ]
