# Generated by Django 5.2.5 on 2025-11-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_customerinvoice_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='reversing_journal_entry',
        ),
        migrations.RemoveField(
            model_name='finishedproductdispatch',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='finishedproductdispatch',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='finishedproductdispatch',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='finishedproductdispatch',
            name='reversing_journal_entry',
        ),
        migrations.AlterField(
            model_name='customerpaymentapplication',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.customerinvoice', verbose_name='Invoice'),
        ),
        migrations.CreateModel(
            name='CustomerCreditMemoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount Applied')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Application Date')),
                ('credit_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.customercreditmemo', verbose_name='Credit Memo')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memo_applications', to='inventory.customerinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Customer Credit Memo Application',
                'verbose_name_plural': 'Customer Credit Memo Applications',
                'unique_together': {('credit_memo', 'invoice')},
            },
        ),
        migrations.DeleteModel(
            name='CreditMemoApplication',
        ),
    ]
