# Generated by Django 5.2.5 on 2025-11-19 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0065_alter_productionreturn_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landedcostinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("awaiting_allocation", "Awaiting Allocation"),
                    ("allocated", "Allocated"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=25,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="LandedCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="Allocated Amount"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="inventory.landedcostinvoice",
                        verbose_name="Source Invoice",
                    ),
                ),
                (
                    "receipt_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landed_cost_allocations",
                        to="inventory.inventorylog",
                        verbose_name="Target Receipt",
                    ),
                ),
            ],
            options={
                "db_table": "landed_cost_allocations",
            },
        ),
    ]
