# Generated by Django 5.2.5 on 2025-08-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_order_number', models.CharField(max_length=255, verbose_name='Shop Order Number')),
                ('batch_number', models.CharField(max_length=255, verbose_name='Batch Number')),
                ('creation_date', models.DateTimeField(verbose_name='Creation Date')),
                ('is_customized', models.BooleanField(default=False, verbose_name='Is Customized')),
                ('is_continuation', models.BooleanField(default=False, verbose_name='Is Continuation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batches',
                'ordering': ['-creation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Product Code')),
                ('product_type', models.CharField(choices=[('مواد خام', 'Raw Material'), ('تعبئه و تغليف', 'Packaging'), ('منتج نهائي', 'Final Product')], max_length=50, verbose_name='Product Type')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit of Measurement')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('qc_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='QC Number')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='inventory.company', verbose_name='Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'db_table': 'inventory_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('balance_date', models.DateTimeField(verbose_name='Balance Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Opening Balance',
                'verbose_name_plural': 'Opening Balances',
                'db_table': 'opening_balances',
                'ordering': ['product__name', '-balance_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_quantity', models.FloatField(verbose_name='Theoretical Quantity')),
                ('actual_quantity', models.FloatField(blank=True, null=True, verbose_name='Actual Quantity')),
                ('source_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('inventory_log', 'Inventory Log')], max_length=20, verbose_name='Source Type')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.batch', verbose_name='Batch')),
                ('source_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='inventory.inventorylog', verbose_name='Source Inventory Log')),
                ('primitive_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='inventory.product', verbose_name='Primitive Product')),
            ],
            options={
                'verbose_name': 'Batch Item',
                'verbose_name_plural': 'Batch Items',
                'db_table': 'batch_items',
            },
        ),
        migrations.CreateModel(
            name='ProductionReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity Returned')),
                ('return_date', models.DateTimeField(verbose_name='Return Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_returns', to='inventory.product', verbose_name='Product')),
                ('source_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_returns', to='inventory.inventorylog', verbose_name='Original Source Log')),
            ],
            options={
                'verbose_name': 'Production Return',
                'verbose_name_plural': 'Production Returns',
                'db_table': 'production_returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='inventory.product', verbose_name='Final Product')),
            ],
            options={
                'verbose_name': 'Shop Order Template',
                'verbose_name_plural': 'Shop Order Templates',
                'db_table': 'shop_order_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.shopordertemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_quantity', models.FloatField(verbose_name='Theoretical Quantity')),
                ('primitive_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='inventory.product', verbose_name='Primitive Product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shopordertemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Item',
                'verbose_name_plural': 'Template Items',
                'db_table': 'template_items',
            },
        ),
    ]
