# Generated by Django 5.2.5 on 2025-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
                'db_table': 'product_tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('مواد خام', 'مواد خام'), ('تعبئه و تغليف', 'تعبئه و تغليف'), ('منتج نهائي', 'منتج نهائي')], max_length=50, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.producttag', verbose_name='Tags'),
        ),
    ]
