# Generated by Django 5.2.5 on 2025-09-18 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_bankreconciliation_reconciled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fiscal Year Name')),
                ('start_date', models.DateField(unique=True, verbose_name='Start Date')),
                ('end_date', models.DateField(unique=True, verbose_name='End Date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Closed')),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'db_table': 'fiscal_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='financialperiod',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending_close', 'Pending Close'), ('closed', 'Closed'), ('locked', 'Permanently Locked')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterModelTable(
            name='bankreconciliation',
            table='bank_reconciliations',
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='inventory.fiscalyear', verbose_name='Fiscal Year'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PeriodClosingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.CharField(choices=[('closed', 'Closed'), ('reopened', 'Re-opened'), ('locked', 'Permanently Locked')], max_length=10, verbose_name='Action')),
                ('justification', models.TextField(verbose_name='Justification / Reason')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='inventory.financialperiod', verbose_name='Financial Period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Period Closing Audit Log',
                'verbose_name_plural': 'Period Closing Audit Logs',
                'db_table': 'period_closing_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
