# Generated by Django 5.2.5 on 2025-08-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_producttag_alter_product_product_type_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='inventory_logs', to='inventory.producttag', verbose_name='Tags'),
        ),
    ]
