# Generated by Django 5.2.5 on 2025-09-18 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fiscalyear_remove_financialperiod_is_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodclosingauditlog',
            options={'ordering': ['-action_timestamp'], 'verbose_name': 'Period Closing Audit Log', 'verbose_name_plural': 'Period Closing Audit Logs'},
        ),
        migrations.RemoveField(
            model_name='periodclosingauditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='periodclosingauditlog',
            name='period',
        ),
        migrations.RemoveField(
            model_name='periodclosingauditlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='periodclosingauditlog',
            name='action_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Action Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodclosingauditlog',
            name='action_type',
            field=models.CharField(choices=[('close', 'Close Period'), ('reopen', 'Re-Open Period'), ('lock', 'Permanently Lock')], default='nigga', max_length=20, verbose_name='Action Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodclosingauditlog',
            name='financial_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.financialperiod', verbose_name='Financial Period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodclosingauditlog',
            name='justification',
            field=models.TextField(blank=True, help_text='Required when re-opening a closed period.', null=True, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='periodclosingauditlog',
            name='user',
            field=models.ForeignKey(help_text='The user who performed the action.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterModelTable(
            name='periodclosingauditlog',
            table=None,
        ),
    ]
