# Generated by Django 5.2.5 on 2025-09-02 17:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='cost_at_consumption',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Cost at Consumption'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Unit Cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='moving_average_cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Moving Average Cost'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True, verbose_name='PO Number')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.company', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.FloatField(verbose_name='Quantity Ordered')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Unit Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.product', verbose_name='Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='inventory.purchaseorderitem', verbose_name='Purchase Order Item'),
        ),
    ]
