# Generated by Django 5.2.5 on 2025-09-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_periodclosingauditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialperiod',
            options={'ordering': ['-start_date'], 'permissions': [('can_reopen_period', 'Can re-open a closed financial period'), ('can_permanently_lock_period', 'Can permanently lock a financial period')], 'verbose_name': 'Financial Period', 'verbose_name_plural': 'Financial Periods'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='posted', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='periodclosingauditlog',
            name='action_type',
            field=models.CharField(choices=[('close', 'Close Period'), ('reopen', 'Re-open Period'), ('lock', 'Permanently Lock')], max_length=20, verbose_name='Action Type'),
        ),
    ]
