# Generated by Django 5.2.5 on 2025-09-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batchitem_cost_at_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Total Price'),
            preserve_default=False,
        ),
    ]
