# Generated by Django 5.2.5 on 2025-09-03 15:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_purchaseorderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingbalance',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='total_value',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Total Value'),
        ),
    ]
