# Generated by Django 5.2.5 on 2025-09-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_generalaccountingsettings_inventory_adjustment_gain_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='is_posted_to_gl',
            field=models.BooleanField(default=False, help_text='Indicates if the journal entry for this adjustment has been created.', verbose_name='Posted to General Ledger'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='inventory_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventorycount', verbose_name='Inventory Count Event'),
            preserve_default=False,
        ),
    ]
