# Generated by Django 5.2.5 on 2025-09-03 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_openingbalance_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_batch_number', models.CharField(max_length=255, verbose_name='Individual Batch Number')),
                ('receipt_date', models.DateField(verbose_name='Receipt Date')),
                ('total_cost', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Total Cost of Batch')),
                ('total_quantity_produced', models.FloatField(verbose_name='Total Quantity Produced')),
                ('market_type', models.CharField(choices=[('local', 'محلي'), ('export', 'تصدير')], default='local', max_length=10, verbose_name='Market Type')),
                ('status', models.CharField(choices=[('quarantined', 'تحت الفحص'), ('released', 'مفرج عنه'), ('rejected', 'مرفوض')], default='quarantined', max_length=20, verbose_name='Status')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.batch', verbose_name='Production Plan')),
            ],
            options={
                'verbose_name': 'Finished Product Receipt',
                'verbose_name_plural': 'Finished Product Receipts',
                'db_table': 'finished_product_receipts',
                'ordering': ['-receipt_date', '-id'],
                'unique_together': {('batch', 'individual_batch_number')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptSubBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_batch_identifier', models.CharField(max_length=100, verbose_name='Sub-Batch Identifier')),
                ('quantity', models.FloatField(verbose_name='Quantity in Sub-Batch')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_batches', to='inventory.finishedproductreceipt', verbose_name='Parent Receipt')),
            ],
            options={
                'verbose_name': 'Receipt Sub-Batch',
                'verbose_name_plural': 'Receipt Sub-Batches',
                'db_table': 'receipt_sub_batches',
            },
        ),
    ]
