# Generated by Django 5.2.5 on 2025-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_finishedproductreceipt_receiptsubbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='release_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Release Timestamp'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='status',
            field=models.CharField(choices=[('quarantined', 'تحت الفحص'), ('released', 'مفرج عنه'), ('rejected', 'مرفوض')], default='quarantined', max_length=20, verbose_name='Status'),
        ),
    ]
