# Generated by Django 5.2.5 on 2025-09-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorylog_release_timestamp_inventorylog_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finishedproductreceipt',
            unique_together=set(),
        ),
    ]
