# Generated by Django 5.2.5 on 2025-09-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_finishedproductreceipt_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Customer Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Contact Info')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('so_number', models.CharField(max_length=100, unique=True, verbose_name='Sales Order Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Shipment'), ('partially_shipped', 'Partially Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'sales_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.FloatField(verbose_name='Quantity Ordered')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Unit Price')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='inventory.finishedproductreceipt', verbose_name='Finished Product Batch')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salesorder', verbose_name='Sales Order')),
            ],
            options={
                'verbose_name': 'Sales Order Item',
                'verbose_name_plural': 'Sales Order Items',
                'db_table': 'sales_order_items',
            },
        ),
        migrations.CreateModel(
            name='FinishedProductDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity Dispatched')),
                ('dispatch_date', models.DateTimeField(verbose_name='Dispatch Date')),
                ('cost_at_dispatch', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cost at Dispatch')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='inventory.salesorderitem', verbose_name='Sales Order Item')),
            ],
            options={
                'verbose_name': 'Finished Product Dispatch',
                'verbose_name_plural': 'Finished Product Dispatches',
                'db_table': 'finished_product_dispatches',
                'ordering': ['-dispatch_date'],
            },
        ),
    ]
