# Generated by Django 5.2.5 on 2025-09-25 11:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_allocationdriver_batch_machine_hours_consumed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'verbose_name': 'Bank Transfer', 'verbose_name_plural': 'Bank Transfers'},
        ),
        migrations.AddField(
            model_name='finishedproductreceipt',
            name='allocated_overhead_cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='The portion of manufacturing overhead applied to this receipt.', max_digits=14, verbose_name='Allocated Overhead Cost'),
        ),
        migrations.CreateModel(
            name='ExpenseCategoryAccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salaries', 'رواتب وأجور'), ('utilities', 'كهرباء ومياه واتصالات'), ('rent', 'إيجارات'), ('marketing', 'تسويق وإعلان'), ('transport', 'نقل وشحن'), ('maintenance', 'صيانة (خدمات خارجية)'), ('fees', 'رسوم حكومية وتراخيص'), ('other', 'مصاريف أخرى')], max_length=50, unique=True, verbose_name='Expense Category')),
                ('expense_account', models.ForeignKey(limit_choices_to={'account_type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Default Expense Account')),
            ],
            options={
                'verbose_name': 'Expense Category Accounting Setting',
                'verbose_name_plural': 'Expense Category Accounting Settings',
            },
        ),
    ]
