# Generated by Django 5.2.5 on 2025-09-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_customer_salesorder_salesorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('category', models.CharField(choices=[('salaries', 'رواتب وأجور'), ('utilities', 'كهرباء ومياه واتصالات'), ('rent', 'إيجارات'), ('marketing', 'تسويق وإعلان'), ('transport', 'نقل وشحن'), ('maintenance', 'صيانة (خدمات خارجية)'), ('fees', 'رسوم حكومية وتراخيص'), ('other', 'مصاريف أخرى')], max_length=50, verbose_name='Category')),
                ('classification', models.CharField(choices=[('manufacturing_overhead', 'تكاليف صناعية غير مباشرة'), ('sg_a', 'مصاريف بيعية وعمومية وإدارية')], max_length=50, verbose_name='Classification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'General Expense Log',
                'verbose_name_plural': 'General Expense Logs',
                'db_table': 'expense_logs',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('مواد خام', 'مواد خام'), ('تعبئه و تغليف', 'تعبئه و تغليف'), ('منتج نهائي', 'منتج نهائي'), ('قطع غيار و صيانة', 'قطع غيار و صيانة'), ('مستهلكات', 'مستهلكات')], max_length=50, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='InventoryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.FloatField(verbose_name='Quantity Consumed')),
                ('consumption_date', models.DateTimeField(verbose_name='Consumption Date')),
                ('department', models.CharField(choices=[('production', 'الإنتاج'), ('engineering', 'الهندسة والصيانة'), ('admin', 'الإدارة'), ('qc', 'الجودة'), ('other', 'أخرى')], max_length=50, verbose_name='Department')),
                ('cost_at_consumption', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Cost at Consumption')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.product', verbose_name='Product')),
                ('source_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.inventorylog', verbose_name='Source Inventory Log')),
            ],
            options={
                'verbose_name': 'Inventory Consumption',
                'verbose_name_plural': 'Inventory Consumptions',
                'db_table': 'inventory_consumptions',
                'ordering': ['-consumption_date'],
            },
        ),
    ]
