# Generated by Django 5.2.5 on 2025-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_banktransfer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-creation_date', '-id'], 'verbose_name': 'Production Plan', 'verbose_name_plural': 'Production Plans'},
        ),
        migrations.AddField(
            model_name='batch',
            name='labor_hours_consumed',
            field=models.FloatField(blank=True, help_text='Enter the actual labor hours used for this production run.', null=True, verbose_name='Labor Hours Consumed'),
        ),
        migrations.AddField(
            model_name='finishedproductreceipt',
            name='bottle_size_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the size of a single bottle/unit in milliliters.', null=True, verbose_name='Bottle Size (mL)'),
        ),
        migrations.AddField(
            model_name='finishedproductreceipt',
            name='number_of_bottles',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the total number of bottles/units produced in this receipt.', null=True, verbose_name='Number of Bottles'),
        ),
        migrations.AlterModelTable(
            name='batch',
            table=None,
        ),
    ]
