# Generated by Django 5.2.5 on 2025-09-08 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0011_expenselog_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Period Name')),
                ('start_date', models.DateField(unique=True, verbose_name='Start Date')),
                ('end_date', models.DateField(unique=True, verbose_name='End Date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Closed')),
            ],
            options={
                'verbose_name': 'Financial Period',
                'verbose_name_plural': 'Financial Periods',
                'db_table': 'financial_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='base_unit_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Base Unit Price (before VAT)'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='vat_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='vat_treatment',
            field=models.CharField(choices=[('recoverable', 'ضريبة قابلة للخصم'), ('capitalized', 'تضاف للتكلفة')], default='recoverable', max_length=20, verbose_name='VAT Treatment'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='base_price_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Base Price Per Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='VAT Rate (e.g., 0.14 for 14%)'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Withholding Tax Rate (e.g., 0.01 for 1%)'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='base_price_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Base Price Per Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='VAT Rate (e.g., 0.14 for 14%)'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Account Code')),
                ('account_type', models.CharField(choices=[('asset', 'الأصول'), ('liability', 'الالتزامات'), ('equity', 'حقوق الملكية'), ('revenue', 'الإيرادات'), ('expense', 'المصروفات')], max_length=20, verbose_name='Account Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.account', verbose_name='Parent Account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'chart_of_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='override_cogs_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.account', verbose_name='Override COGS/Expense Account'),
        ),
        migrations.AddField(
            model_name='product',
            name='override_inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.account', verbose_name='Override Inventory Account'),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('entry_type', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=6, verbose_name='Entry Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='inventory.account', verbose_name='Account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'db_table': 'journal_entry_lines',
                'ordering': ['journal_entry', 'entry_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeAccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('مواد خام', 'مواد خام'), ('تعبئه و تغليف', 'تعبئه و تغليف'), ('منتج نهائي', 'منتج نهائي'), ('قطع غيار و صيانة', 'قطع غيار و صيانة'), ('مستهلكات', 'مستهلكات')], max_length=50, unique=True, verbose_name='Product Type')),
                ('cogs_or_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Default COGS/Expense Account')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Default Inventory Account')),
            ],
            options={
                'verbose_name': 'Product Type Accounting Setting',
                'verbose_name_plural': 'Product Type Accounting Settings',
                'db_table': 'product_type_acct_settings',
            },
        ),
    ]
