# Generated by Django 5.2.5 on 2025-09-08 18:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_financialperiod_remove_inventorylog_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bank/Cash Box Name')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='Currency')),
                ('gl_account', models.OneToOneField(limit_choices_to={'code__startswith': '102'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.account', verbose_name='GL Control Account')),
            ],
            options={
                'verbose_name': 'Bank Account / Cash Box',
                'verbose_name_plural': 'Bank Accounts / Cash Boxes',
                'db_table': 'bank_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True, verbose_name='Asset Tag / Barcode')),
                ('name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('purchase_cost', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Original Purchase Cost')),
                ('depreciation_start_date', models.DateField(verbose_name='Depreciation Start Date')),
                ('useful_life_years', models.PositiveIntegerField(verbose_name='Useful Life (Years)')),
                ('salvage_value', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Salvage Value')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('under_construction', 'Under Construction'), ('idle', 'Idle'), ('sold', 'Sold'), ('retired', 'Retired/Scrapped')], default='in_service', max_length=20, verbose_name='Status')),
                ('gl_account', models.ForeignKey(limit_choices_to={'code__startswith': '101'}, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='inventory.account', verbose_name='GL Control Account')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'db_table': 'fixed_assets',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[('out', 'Payment Made (to Supplier)'), ('in', 'Payment Received (from Customer)'), ('transfer', 'Bank Transfer'), ('other', 'Other Transaction')], max_length=10, verbose_name='Payment Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.bankaccount', verbose_name='Bank/Cash Account')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.customer', verbose_name='Customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.company', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
