# Generated by Django 5.2.5 on 2025-09-08 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_employee_bankaccount_fixedasset_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='gl_account',
            field=models.OneToOneField(limit_choices_to={'code__startswith': '10201'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.account', verbose_name='GL Control Account'),
        ),
        migrations.CreateModel(
            name='GeneralAccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_payable', models.ForeignKey(help_text="e.g., '20201 - حسابات الموردين (ذمم دائنة)'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Default Accounts Payable (A/P) Account')),
                ('accounts_receivable', models.ForeignKey(help_text="e.g., '10203 - حسابات العملاء (ذمم مدينة)'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Default Accounts Receivable (A/R) Account')),
                ('vat_payable', models.ForeignKey(help_text='The liability account for VAT collected from sales.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='VAT on Outputs (Payable) Account')),
                ('vat_receivable', models.ForeignKey(help_text="e.g., '1020404 - ضريبة القيمة المضافة (المدخلات)'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='VAT on Inputs (Receivable) Account')),
                ('wip_inventory', models.ForeignKey(help_text="e.g., '1020205 - مخزون انتاج تحت التشغيل'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Work-in-Progress (WIP) Inventory Account')),
            ],
            options={
                'verbose_name': 'General Accounting Setting',
                'verbose_name_plural': 'General Accounting Settings',
                'db_table': 'general_accounting_settings',
            },
        ),
    ]
