# Generated by Django 5.2.5 on 2025-09-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_bankaccount_gl_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryconsumption',
            name='consumption_type',
            field=models.CharField(choices=[('expense', 'Expense (Repair)'), ('capitalize', 'Capitalize (Enhancement)')], default='expense', max_length=20, verbose_name='Consumption Type'),
        ),
        migrations.AddField(
            model_name='inventoryconsumption',
            name='fixed_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='inventory.fixedasset', verbose_name='Target Fixed Asset (if capitalized)'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='status',
            field=models.CharField(choices=[('quarantined', 'تحت الفحص'), ('released', 'مفرج عنه'), ('rejected', 'مرفوض'), ('scrapped', 'خردة')], default='quarantined', max_length=20, verbose_name='Status'),
        ),
    ]
