# Generated by Django 5.2.5 on 2025-09-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_overheadallocationrun_calculated_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overheadallocationrun',
            name='application_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Inventory Application Journal Entry'),
        ),
        migrations.AlterField(
            model_name='overheadallocationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Rate Calculated'), ('posted', 'Posted to GL'), ('applied', 'Applied to Inventory')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
