# Generated by Django 5.2.5 on 2025-09-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventoryconsumption_consumption_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='finished_goods_inventory',
            field=models.ForeignKey(default=33, help_text="e.g., '1020206 - مخزون منتج نهائي'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Finished Goods (FG) Inventory Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='override_sales_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.account', verbose_name='Override Sales Revenue Account'),
        ),
        migrations.AddField(
            model_name='producttypeaccountingsettings',
            name='sales_revenue_account',
            field=models.ForeignKey(blank=True, help_text="Required for 'Final Product' types.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Default Sales Revenue Account'),
        ),
    ]
