# Generated by Django 5.2.5 on 2025-09-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_generalaccountingsettings_finished_goods_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='parent_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuation_batches', to='inventory.batch', verbose_name='Parent Batch (for continuations)'),
        ),
    ]
