# Generated by Django 5.2.5 on 2025-09-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_finishedproductreceipt_bottle_size_ml_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalaccountingsettings',
            name='scrap_expense_account',
        ),
    ]
