# Generated by Django 5.2.5 on 2025-09-12 22:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0017_batch_parent_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='accumulated_depreciation_account',
            field=models.ForeignKey(default=54, limit_choices_to={'code__startswith': '20205'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Accumulated Depreciation Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_expense_account',
            field=models.ForeignKey(default=54, limit_choices_to={'account_type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Depreciation Expense Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='Transfer Date')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.bankaccount', verbose_name='Destination Account (To)')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.bankaccount', verbose_name='Source Account (From)')),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'db_table': 'bank_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Total Invoice Amount')),
                ('amount_paid', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.customer', verbose_name='Customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.salesorder', verbose_name='Related Sales Order')),
            ],
            options={
                'verbose_name': 'Customer Invoice',
                'verbose_name_plural': 'Customer Invoices',
                'db_table': 'customer_invoices',
                'ordering': ['-invoice_date'],
                'unique_together': {('customer', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount for this item')),
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='inventory.finishedproductdispatch', verbose_name='Finished Product Dispatch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.customerinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Customer Invoice Item',
                'verbose_name_plural': 'Customer Invoice Items',
                'db_table': 'customer_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount Applied')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Application Date')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='inventory.customerinvoice', verbose_name='Invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_applications', to='inventory.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Customer Payment Application',
                'verbose_name_plural': 'Customer Payment Applications',
                'db_table': 'customer_payment_applications',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Total Invoice Amount')),
                ('amount_paid', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.company', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'db_table': 'supplier_invoices',
                'ordering': ['-invoice_date'],
                'unique_together': {('supplier', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount Applied')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Application Date')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.payment', verbose_name='Payment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='inventory.supplierinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Payment Application',
                'verbose_name_plural': 'Payment Applications',
                'db_table': 'payment_applications',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount for this item')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supplierinvoice', verbose_name='Invoice')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='inventory.inventorylog', verbose_name='Inventory Receipt (Log)')),
            ],
            options={
                'verbose_name': 'Supplier Invoice Item',
                'verbose_name_plural': 'Supplier Invoice Items',
                'db_table': 'supplier_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='DepreciationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(verbose_name='Period End Date')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Depreciation Amount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_logs', to='inventory.fixedasset', verbose_name='Asset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_logs', to='inventory.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Depreciation Log',
                'verbose_name_plural': 'Depreciation Logs',
                'db_table': 'depreciation_logs',
                'ordering': ['-period_date', 'asset'],
                'unique_together': {('asset', 'period_date')},
            },
        ),
    ]
