# Generated by Django 5.2.5 on 2025-09-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0018_remove_generalaccountingsettings_scrap_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_control_account',
            field=models.BooleanField(default=False, help_text='Designates if this account requires a sub-ledger entry (e.g., A/R, A/P).', verbose_name='Is Control Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='sub_ledger_model',
            field=models.ForeignKey(blank=True, help_text='The model that acts as the sub-ledger for this account (e.g., Customer, Company).', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Sub-Ledger Model'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='sub_ledger_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Sub-Ledger Type'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='sub_ledger_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sub-Ledger ID'),
        ),
    ]
