# Generated by Django 5.2.5 on 2025-09-16 17:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_fixedasset_accumulated_depreciation_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='withholding_tax_payable',
            field=models.ForeignKey(blank=True, help_text='The liability account for withholding tax deducted from supplier payments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Withholding Tax Payable Account'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Withholding Tax Amount'),
        ),
        migrations.AlterField(
            model_name='generalaccountingsettings',
            name='wip_inventory',
            field=models.ForeignKey(help_text="e.g., '102020205 - مخزون انتاج تحت التشغيل'", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Work-in-Progress (WIP) Inventory Account'),
        ),
    ]
