# Generated by Django 5.2.5 on 2025-09-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_transactioncorrection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncorrection',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_transaction_correction', 'Can create transaction corrections for posted documents')], 'verbose_name': 'Transaction Correction', 'verbose_name_plural': 'Transaction Corrections'},
        ),
        migrations.RenameField(
            model_name='transactioncorrection',
            old_name='user',
            new_name='corrected_by',
        ),
        migrations.RenameField(
            model_name='transactioncorrection',
            old_name='correction_timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='transactioncorrection',
            name='adjusting_journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correction_for', to='inventory.journalentry', verbose_name='Adjusting Journal Entry'),
        ),
        migrations.AlterModelTable(
            name='transactioncorrection',
            table='transaction_corrections',
        ),
    ]
