# Generated by Django 5.2.5 on 2025-09-29 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0021_alter_transactioncorrection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='status',
            field=models.CharField(choices=[('in_service', 'In Service'), ('under_construction', 'Under Construction'), ('idle', 'Idle'), ('sold', 'Sold'), ('retired', 'Retired')], default='in_service', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventoryconsumption',
            name='department',
            field=models.CharField(choices=[('production', 'Production'), ('engineering', 'Engineering and Maintenance'), ('admin', 'Administration'), ('qc', 'Quality Control'), ('other', 'Other')], max_length=50, verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='OpeningBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Migration Name / Event')),
                ('migration_date', models.DateField(verbose_name='Migration Go-Live Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_entry', to='inventory.journalentry', verbose_name='Resulting Journal Entry')),
            ],
            options={
                'verbose_name': 'Opening Balance Entry',
                'verbose_name_plural': 'Opening Balance Entries',
                'db_table': 'opening_balance_entries',
                'ordering': ['-migration_date'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6, verbose_name='Entry Type')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Total Amount for this Account')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_lines', to='inventory.account', verbose_name='GL Account')),
                ('opening_balance_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.openingbalanceentry', verbose_name='Opening Balance Entry')),
            ],
            options={
                'verbose_name': 'Opening Balance Entry Line',
                'verbose_name_plural': 'Opening Balance Entry Lines',
                'db_table': 'opening_balance_entry_lines',
                'unique_together': {('opening_balance_entry', 'account')},
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceSubLedgerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount for this Sub-Ledger item')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_ledger_details', to='inventory.openingbalanceentryline', verbose_name='Opening Balance Line')),
            ],
            options={
                'verbose_name': 'Opening Balance Sub-Ledger Detail',
                'verbose_name_plural': 'Opening Balance Sub-Ledger Details',
                'db_table': 'opening_balance_sub_ledger_details',
                'unique_together': {('line', 'content_type', 'object_id')},
            },
        ),
        migrations.DeleteModel(
            name='OpeningBalance',
        ),
    ]
