# Generated by Django 5.2.5 on 2025-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_customerpaymentapplication_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='all_banks_reconciled',
            field=models.BooleanField(default=False, help_text='Have all bank accounts been reconciled for the period?', verbose_name='Banks Reconciled'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='is_depreciation_run',
            field=models.BooleanField(default=False, help_text='Has the monthly depreciation for all fixed assets been calculated and posted?', verbose_name='Depreciation Run'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='is_inventory_valuation_run',
            field=models.BooleanField(default=True, help_text='Is the period-end inventory valuation process complete? (Default: True)', verbose_name='Inventory Valuation Complete'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='is_overhead_posted',
            field=models.BooleanField(default=False, help_text='Has the manufacturing overhead been fully allocated and posted to WIP/FG?', verbose_name='Overhead Allocated'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='no_draft_manual_jes',
            field=models.BooleanField(default=False, help_text="Are there any manual journal entries still in 'Draft' status for this period?", verbose_name='No Draft JEs'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='no_unposted_invoices',
            field=models.BooleanField(default=False, help_text="Are there any supplier or customer invoices still in 'Draft' status for this period?", verbose_name='No Unposted Invoices'),
        ),
    ]
