# Generated by Django 5.2.5 on 2025-10-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0029_remove_salesreturnitem_journal_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryconsumption',
            name='cost_pool',
            field=models.ForeignKey(blank=True, help_text='For non-amortizable items, select a cost pool to directly expense this consumption to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.costpool', verbose_name='Direct Expense Cost Pool'),
        ),
        migrations.AddField(
            model_name='periodclosechecklist',
            name='is_accruals_run',
            field=models.BooleanField(default=False, verbose_name='Expense Accruals Have Been Run'),
        ),
        migrations.AddField(
            model_name='periodclosechecklist',
            name='is_amortization_run',
            field=models.BooleanField(default=False, verbose_name='Prepaid Expense Amortization Has Been Run'),
        ),
        migrations.AddField(
            model_name='periodclosechecklist',
            name='is_ap_aging_reviewed',
            field=models.BooleanField(default=False, verbose_name='A/P Aging Report Reviewed'),
        ),
        migrations.AddField(
            model_name='periodclosechecklist',
            name='is_ar_aging_reviewed',
            field=models.BooleanField(default=False, verbose_name='A/R Aging Report Reviewed'),
        ),
        migrations.AddField(
            model_name='periodclosechecklist',
            name='is_fixed_assets_reviewed',
            field=models.BooleanField(default=False, verbose_name='Fixed Assets Review Completed'),
        ),
        migrations.AddField(
            model_name='periodclosechecklist',
            name='is_inventory_reconciled',
            field=models.BooleanField(default=False, verbose_name='Inventory Reconciliation Reviewed'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_amortizable',
            field=models.BooleanField(default=False, help_text='If checked, consuming this item will create a prepaid asset to be amortized over time.', verbose_name='Is Amortizable'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='all_banks_reconciled',
            field=models.BooleanField(default=False, verbose_name='All Bank Accounts Reconciled'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='is_depreciation_run',
            field=models.BooleanField(default=False, verbose_name='Monthly Depreciation Has Been Run'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='is_inventory_valuation_run',
            field=models.BooleanField(default=True, help_text='This is assumed to be true as valuation is perpetual.', verbose_name='Inventory Valuation is Finalized'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='is_overhead_posted',
            field=models.BooleanField(default=False, verbose_name='Overhead Allocation Has Been Posted'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='no_draft_manual_jes',
            field=models.BooleanField(default=False, verbose_name='No Draft Manual Journal Entries'),
        ),
        migrations.AlterField(
            model_name='periodclosechecklist',
            name='no_unposted_invoices',
            field=models.BooleanField(default=False, verbose_name='No Unposted Invoices'),
        ),
        migrations.CreateModel(
            name='AccruedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Expense Description')),
                ('estimated_monthly_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Estimated Monthly Amount')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('target_expense_account', models.ForeignKey(help_text='The expense account to debit during the monthly accrual (e.g., Utilities Expense).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Target Expense Account')),
                ('target_liability_account', models.ForeignKey(help_text='The liability account to credit (e.g., Accrued Expenses Payable).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Target Accrual Liability Account')),
            ],
            options={
                'verbose_name': 'Accrued Expense',
                'verbose_name_plural': 'Accrued Expenses',
            },
        ),
        migrations.CreateModel(
            name='PrepaidExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Total Prepaid Amount')),
                ('amortization_start_date', models.DateField(verbose_name='Amortization Start Date')),
                ('amortization_end_date', models.DateField(verbose_name='Amortization End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('amortized', 'Fully Amortized'), ('written_off', 'Written Off')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('expense_account', models.ForeignKey(help_text='The expense account to debit during amortization (e.g., Insurance Expense).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Target Expense Account')),
                ('source_consumption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expense', to='inventory.inventoryconsumption', verbose_name='Source Inventory Consumption')),
                ('source_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expense', to='inventory.payment', verbose_name='Source Payment')),
            ],
            options={
                'verbose_name': 'Prepaid Expense',
                'verbose_name_plural': 'Prepaid Expenses',
            },
        ),
        migrations.CreateModel(
            name='AccrualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Accrued Amount')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrual_logs', to='inventory.financialperiod', verbose_name='Financial Period')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Accrual Journal Entry')),
                ('settling_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_accruals', to='inventory.supplierinvoice', verbose_name='Settling Invoice')),
                ('true_up_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='True-Up Journal Entry')),
                ('accrued_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_logs', to='inventory.accruedexpense', verbose_name='Accrued Expense')),
            ],
            options={
                'verbose_name': 'Accrual Log',
                'verbose_name_plural': 'Accrual Logs',
                'unique_together': {('accrued_expense', 'financial_period')},
            },
        ),
        migrations.CreateModel(
            name='CostPoolSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='The percentage of the cost to allocate to this pool (e.g., 70.50).', max_digits=5, verbose_name='Percentage')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('cost_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='inventory.costpool', verbose_name='Cost Pool')),
            ],
            options={
                'verbose_name': 'Cost Pool Split',
                'verbose_name_plural': 'Cost Pool Splits',
                'unique_together': {('content_type', 'object_id', 'cost_pool')},
            },
        ),
        migrations.CreateModel(
            name='AmortizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amortized Amount')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amortization_logs', to='inventory.financialperiod', verbose_name='Financial Period')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Amortization Journal Entry')),
                ('prepaid_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_logs', to='inventory.prepaidexpense', verbose_name='Prepaid Expense')),
            ],
            options={
                'verbose_name': 'Amortization Log',
                'verbose_name_plural': 'Amortization Logs',
                'unique_together': {('prepaid_expense', 'financial_period')},
            },
        ),
    ]
