# Generated by Django 5.2.5 on 2025-10-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
