# Generated by Django 5.2.5 on 2025-10-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_expenserequest_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
