# Generated by Django 5.2.5 on 2025-10-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accruallog',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='True-Up Journal Entry'),
        ),
        migrations.AlterField(
            model_name='expenselog',
            name='category',
            field=models.CharField(blank=True, choices=[('salaries', 'رواتب وأجور'), ('utilities', 'كهرباء ومياه واتصالات'), ('rent', 'إيجارات'), ('marketing', 'تسويق وإعلان'), ('transport', 'نقل وشحن'), ('maintenance', 'صيانة (خدمات خارجية)'), ('fees', 'رسوم حكومية وتراخيص'), ('other', 'مصاريف أخرى')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expenselog',
            name='classification',
            field=models.CharField(blank=True, choices=[('manufacturing_overhead', 'تكاليف صناعية غير مباشرة'), ('sg_a', 'مصاريف بيعية وعمومية وإدارية')], max_length=50, null=True, verbose_name='Classification'),
        ),
    ]
