# Generated by Django 5.2.5 on 2025-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_accruallog_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='request_type',
            field=models.CharField(choices=[('DIRECT_EXPENSE', 'Direct Expense'), ('INVENTORY_EXPENSE', 'Inventory Consumption to Expense'), ('INVENTORY_CAPITALIZE', 'Inventory Consumption to Capitalize'), ('INVENTORY_PREPAID', 'Inventory Consumption to Prepaid'), ('INVOICE_PREPAID', 'Prepaid Expense from Invoice'), ('ACCRUAL', 'Expense Accrual')], db_index=True, max_length=30),
        ),
    ]
