# Generated by Django 5.2.5 on 2025-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_fix_accruedexpense_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accruedexpense',
            name='total_estimated_amount',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Total Estimated Amount'),
        ),
    ]
