# Generated by Django 5.2.5 on 2025-10-18 07:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_accruedexpense_total_estimated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditmemo',
            name='base_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Base Amount (before VAT)'),
        ),
        migrations.AddField(
            model_name='customercreditmemo',
            name='vat_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='VAT Amount'),
        ),
    ]
