# Generated by Django 5.2.5 on 2025-10-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_inventorylog_costing_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='source_purchase_return_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment', to='inventory.purchasereturnitem', verbose_name='Source Purchase Return Item'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason_code',
            field=models.CharField(choices=[('shrinkage', 'نقص/خسارة'), ('damage', 'بضاعة تالفة'), ('data_entry_error', 'تصحيح خطأ إدخال بيانات'), ('overage_found', 'زيادة وجدت أثناء الجرد'), ('sales_return_stock', 'إرجاع إلى المخزون من المبيعات'), ('return_to_supplier', 'مرتجع إلى المورد'), ('other', 'أخرى')], max_length=30, verbose_name='Reason Code'),
        ),
    ]
