# Generated by Django 5.2.5 on 2025-10-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_inventoryadjustment_source_purchase_return_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Indicates that no further receipts are expected for this line item, even if under-delivered.', verbose_name='Is Closed'),
        ),
    ]
