# Generated by Django 5.2.5 on 2025-10-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_batch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
        ),
        migrations.AddField(
            model_name='batch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_batches', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='batch',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_batches', to=settings.AUTH_USER_MODEL, verbose_name='Completed By'),
        ),
        migrations.AddField(
            model_name='batch',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='batch',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Launch Date'),
        ),
        migrations.AddField(
            model_name='batch',
            name='launched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='launched_batches', to=settings.AUTH_USER_MODEL, verbose_name='Launched By'),
        ),
        migrations.AddField(
            model_name='batch',
            name='status_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Status Change'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_production', 'In Production'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
