# Generated by Django 5.2.5 on 2025-10-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_batch_approval_date_batch_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='launched_by',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='status_change_date',
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
