# Generated by Django 5.2.5 on 2025-10-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_remove_batch_approval_date_remove_batch_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='batch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='batch',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='batch',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_batches', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
