# Generated by Django 5.2.5 on 2025-10-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_batch_approved_at_batch_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='accrued_landed_costs_account',
            field=models.ForeignKey(blank=True, help_text='A liability account to accrue estimated landed costs at time of receipt.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Accrued Landed Costs Account'),
        ),
        migrations.AddField(
            model_name='generalaccountingsettings',
            name='landed_cost_variance_account',
            field=models.ForeignKey(blank=True, help_text='An expense account to record differences between estimated and actual landed costs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.account', verbose_name='Landed Cost Variance Account'),
        ),
        migrations.AddField(
            model_name='landedcostinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landed_cost_invoices', to='inventory.purchaseorder', verbose_name='Related Purchase Order'),
        ),
        migrations.AlterField(
            model_name='finishedproductreceipt',
            name='status',
            field=models.CharField(choices=[('quarantined', 'تحت الفحص'), ('released', 'مفرج عنه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='quarantined', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='landedcostinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid')], default='draft', max_length=25, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemLandedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Estimated Amount')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.landedcosttype', verbose_name='Landed Cost Type')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_estimates', to='inventory.purchaseorderitem', verbose_name='Purchase Order Item')),
            ],
            options={
                'verbose_name': 'PO Item Landed Cost Estimate',
                'verbose_name_plural': 'PO Item Landed Cost Estimates',
                'db_table': 'po_item_landed_cost_estimates',
                'unique_together': {('purchase_order_item', 'cost_type')},
            },
        ),
        migrations.DeleteModel(
            name='LandedCostAllocation',
        ),
    ]
