# Generated by Django 5.2.5 on 2025-10-31 10:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_generalaccountingsettings_accrued_landed_costs_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='landed_cost_allocation_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text="The percentage of the PO's total landed costs to allocate to this line item.", max_digits=7, verbose_name='Landed Cost Allocation %'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLandedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Estimated Amount')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.landedcosttype', verbose_name='Landed Cost Type')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_costs', to='inventory.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'PO Landed Cost Estimate',
                'verbose_name_plural': 'PO Landed Cost Estimates',
                'db_table': 'po_landed_costs',
                'unique_together': {('purchase_order', 'cost_type')},
            },
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItemLandedCost',
        ),
    ]
