# Generated by Django 5.2.5 on 2025-11-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_purchaseorderitem_landed_cost_allocation_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='reversing_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Reversing Journal Entry'),
        ),
        migrations.AddField(
            model_name='finishedproductdispatch',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='finishedproductdispatch',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='finishedproductdispatch',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
        migrations.AddField(
            model_name='finishedproductdispatch',
            name='reversing_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.journalentry', verbose_name='Reversing Journal Entry'),
        ),
        migrations.AlterField(
            model_name='customerpaymentapplication',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='inventory.customerinvoice', verbose_name='Invoice'),
        ),
        migrations.CreateModel(
            name='CreditMemoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount Applied')),
                ('application_date', models.DateField(auto_now_add=True, verbose_name='Application Date')),
                ('credit_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.customercreditmemo', verbose_name='Credit Memo')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_memo_applications', to='inventory.customerinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Credit Memo Application',
                'verbose_name_plural': 'Credit Memo Applications',
                'db_table': 'credit_memo_applications',
                'unique_together': {('credit_memo', 'invoice')},
            },
        ),
    ]
