# Generated by Django 5.2.5 on 2025-11-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_remove_customerinvoice_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-creation_date', '-id'], 'permissions': [('can_submit_batch', 'Can submit batch for approval'), ('can_approve_batch', 'Can approve or reject a batch'), ('can_start_production', 'Can start production for a batch'), ('can_cancel_batch', 'Can cancel a batch')], 'verbose_name': 'Production Plan', 'verbose_name_plural': 'Production Plans'},
        ),
    ]
