# Generated by Django 5.2.5 on 2025-11-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0063_alter_batch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchitem",
            name="actual_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Actual Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="batchitem",
            name="theoretical_quantity",
            field=models.DecimalField(
                decimal_places=4, max_digits=14, verbose_name="Theoretical Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="finishedproductreceipt",
            name="total_quantity_produced",
            field=models.DecimalField(
                decimal_places=4, max_digits=14, verbose_name="Total Quantity Produced"
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4, max_digits=14, verbose_name="Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="productionreturn",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4, max_digits=14, verbose_name="Quantity Returned"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity_ordered",
            field=models.DecimalField(
                decimal_places=4, max_digits=14, verbose_name="Quantity Ordered"
            ),
        ),
        migrations.AlterField(
            model_name="templateitem",
            name="theoretical_quantity",
            field=models.DecimalField(
                decimal_places=4, max_digits=14, verbose_name="Theoretical Quantity"
            ),
        ),
    ]
