# Generated by Django 5.2.5 on 2025-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0064_alter_batchitem_actual_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionreturn",
            name="quantity",
            field=models.FloatField(verbose_name="Quantity Returned"),
        ),
    ]
