# Generated by Django 5.2.5 on 2025-11-19 02:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0066_alter_landedcostinvoice_status_landedcostallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="landedcostinvoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=14,
                verbose_name="Amount Paid",
            ),
        ),
        migrations.AlterField(
            model_name="landedcostinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("awaiting_allocation", "Awaiting Allocation"),
                    ("allocated", "Allocated"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=25,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="LandedCostPaymentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_applied",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="Amount Applied"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_applications",
                        to="inventory.landedcostinvoice",
                        verbose_name="Landed Cost Invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landed_cost_applications",
                        to="inventory.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "db_table": "landed_cost_payment_applications",
            },
        ),
    ]
