# gipcco_project/gipcco_project/settings.py

"""
Django settings for gipcco_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# --- NEW IMPORT FOR MESSAGES ---
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@e^a57h=v73b*0@7$m0=r%_0o6(tq99i_g5p+!5a_#)h+n^h0*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Add your laptop's hotspot IP address here
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.137.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admincharts',
    'import_export',
    # --- OUR APP ---
    'inventory.apps.InventoryConfig',
     # Add this line
    'django.contrib.humanize', # For using filters like intcomma
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'inventory.middleware.FinancialPeriodExceptionHandlerMiddleware', # --- NEW ---
]

ROOT_URLCONF = 'gipcco_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # --- ADD TEMPLATES DIRECTORY ---
        # We add the project-level templates directory here.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gipcco_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'inventory.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# --- ADD THIS ---
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# ---------------

# This is the path where collectstatic will gather all files.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- NEW SETTING FOR MESSAGE TAGS ---
# This maps Django's message levels to Bootstrap alert classes.
# The default 'error' level is mapped to 'danger' for correct styling.
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# --- NEW LOGGING CONFIGURATION ---
# Add this entire block to the end of your settings.py file.

# Ensure the 'logs' directory exists
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'gipcco.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        # --- NEW: Logger for our 'inventory' app ---
        'inventory': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG', # Set to DEBUG to capture all levels of logs from our app
            'propagate': True,
        },
    },
}

# --- NEW: Disable file logging during tests ---
# This checks if 'test' is in the command-line arguments (e.g., 'manage.py test')
# and reconfigures the logging to prevent file locks and speed up tests.
import sys
if 'test' in sys.argv:
    LOGGING['handlers']['file'] = {
        'level': 'INFO',
        'class': 'logging.NullHandler', # Send file logs to nowhere during tests
    }
    # Optionally, you can also reduce the console output verbosity during tests
    # LOGGING['handlers']['console']['level'] = 'WARNING'


# --- JAZZMIN SETTINGS ---
# These settings customize the look and feel of the Django admin interface.
JAZZMIN_SETTINGS = {
    # TITLE AND LOGO
    "site_title": "Inventory Admin",
    "site_header": "Inventory Management",
    "site_brand": "GIPCCO ADMIN",
    "site_icon": "fas fa-warehouse", # Example: FontAwesome icon for your site
    # Add a logo
    "welcome_sign": "Welcome to the Inventory Management System Admin!",
    "logo": "img/ims_logo.png", # Path to your logo in static files
    "logo_max_height": "50px", # Max height for the logo in the top bar

    # UI THEME
    "ui_styling": "bootstrap5", # Options: "bootstrap4", "bootstrap5"
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary", # Options: "navbar-primary", "navbar-dark", etc.
    "accent": "accent-primary", # Accent color for links, buttons
    "login_logo": "img/ims_logo.png", # Logo for the login page
    "login_logo_max_height": "120px",

    # SIDEBAR
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,

    # TOPNAV
    "topnav_right_bar": False, # Show/hide right-side navbar items (e.g., messages)
    "show_sidebar": True,
    "navigation_expanded": False, # Start with sidebar collapsed

    # User Menu
    "user_menu_avatar": "img/default_avatar.png", # Path to a default user avatar

    # Custom Icons for models (using FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "companies.Company": "fas fa-building",
        "products.Product": "fas fa-box-open",
        "products.ProductTag": "fas fa-tag",
        "inventory.InventoryLog": "fas fa-clipboard-list",
        "inventory.ShopOrderTemplate": "fas fa-receipt",
        "inventory.TemplateItem": "fas fa-clipboard-list",
        "inventory.Batch": "fas fa-boxes",
        "inventory.BatchItem": "fas fa-box",
        "inventory.OpeningBalance": "fas fa-balance-scale",
        "inventory.ProductionReturn": "fas fa-undo-alt",
        "inventory.PurchaseOrder": "fas fa-shopping-cart",
        "inventory.PurchaseOrderItem": "fas fa-cart-plus",
        "inventory.FinishedProductReceipt": "fas fa-dolly-flatbed",
        "inventory.ReceiptSubBatch": "fas fa-pallet",
    },

    # Optional: Order your apps/models in the sidebar
    "order_with_respect_to": ["inventory", "products", "companies", "auth"],

    # # UI Tweaks (buttons, dark mode, etc.)
    # "actions_sticky_top": True,
    # "search_model_names": ["products.Product", "inventory.Batch", "inventory.PurchaseOrder"], # Models to include in global search
}

# Add UI Tweaks for a more granular look and feel
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "navbar_variants": ["navbar-dark", "navbar-primary", "navbar-white", "navbar-light"],
    "sidebar_variants": ["sidebar-dark-primary", "sidebar-light-primary", "sidebar-dark-info"],
    "theme": "darkly", # Example: "united", "materia", "flatly", "darkly", "cosmo", "yeti", "lumen", "litera", "simplex", "solar", "superhero", "spacelab"
    # "no_navbar_border": False,
    # "navbar_fixed": True,
    # "layout_boxed": False,
    # "footer_fixed": False,
    # "sidebar_nav_accordion": True,
    # "body_classes": "text-sm", # Adjust font size globally
    # "button_classes": {
    #     "primary": "btn-outline-primary",
    #     "secondary": "btn-outline-secondary",
    #     "info": "btn-info",
    #     "warning": "btn-warning",
    #     "danger": "btn-danger",
    #     "success": "btn-success"
    # },
    # "alert_classes": {
    #     "success": "alert-success",
    #     "info": "alert-info",
    #     "warning": "alert-warning",
    #     "danger": "alert-danger"
    # },

}
